const config = {
  glossbossBlue: '#5a1aed',
  glossbossBlueLighter: '#7236ff',
  glossbossBlueDarker: '#5620d5',
  imgHoverFilter: 'sepia(30%) brightness(70%)',
  black: '#130027',
  lightGray: '#c3c3c3',
  lighterGray: 'rgba(0,0,0,.04)',
  lighterLightGray: '#f9f9fa',
  darkGray: '#262626',
  linkColor: '#5a1aed',
  textColor: '#262626',
  darkerGray: '#1C202f',
  lightBorder: '1px solid rgba(0, 0, 0, 0.09)',
  reloadPosts: 15,
  heroGradient: 'rgba(32.2%, 0%, 83.5%, .7)',
  mobileMQ: '811px',
  borderBottom: '3px solid #dce6f4',
  cardBorder: '1px solid #dce6f4',
  categoryPages: require('./data/categories'),
  categories: [
    'Index',
    'Videos',
    'Podcast',
    'Allgemein',
    'Anleitungen',
    'Pflegeberichte',
    'Produkttest',
  ],
  activeBosse: require('./data/glossbosse'),
  navbarLinks: [
    { href: '/mischungsrechner', title: 'Mischungsrechner' },
    { href: '/glossbosse', title: 'Glossbosse' },
  ],
  siteUrl: 'https://glossboss.de/',
  addEmoji: require('./components/addEmoji'),
}

module.exports = config
